version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: sanjay-rag-api
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - pgvector
      - redis
      
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatbot

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      
  redis:
    image: redis:7
    container_name: redis-chatbot
    ports:
      - "6379:6379"
volumes:
  pgdata: